/**
 * Códigos de error estandarizados para toda la aplicación
 * Estructura: [MODULE]_[FEATURE]_[ERROR_TYPE]
 */

// ============== BRIDGE ERRORS ==============
export const BRIDGE_ERROR_CODES = {
  // General bridge errors
  BRIDGE_NOT_INITIALIZED: 'BRIDGE_NOT_INITIALIZED',
  BRIDGE_CONFIG_INVALID: 'BRIDGE_CONFIG_INVALID',
  BRIDGE_INTERNAL_ERROR: 'BRIDGE_INTERNAL_ERROR',
  BRIDGE_TIMEOUT: 'BRIDGE_TIMEOUT',

  // Aggregation errors
  AGGREGATION_FAILED: 'AGGREGATION_FAILED',
  NO_ROUTES_FOUND: 'NO_ROUTES_FOUND',
  INVALID_ROUTE: 'INVALID_ROUTE',

  // Input validation errors
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_CHAIN: 'INVALID_CHAIN',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
} as const;

// ============== ADAPTER ERRORS - STELLAR ==============
export const STELLAR_ADAPTER_ERROR_CODES = {
  // Connection errors
  STELLAR_CONNECTION_FAILED: 'STELLAR_CONNECTION_FAILED',
  STELLAR_NETWORK_ERROR: 'STELLAR_NETWORK_ERROR',
  STELLAR_RPC_ERROR: 'STELLAR_RPC_ERROR',

  // Operation errors
  STELLAR_OPERATION_FAILED: 'STELLAR_OPERATION_FAILED',
  STELLAR_INVALID_MEMO: 'STELLAR_INVALID_MEMO',
  STELLAR_INSUFFICIENT_BALANCE: 'STELLAR_INSUFFICIENT_BALANCE',
  STELLAR_INVALID_TRANSACTION: 'STELLAR_INVALID_TRANSACTION',

  // Fee errors
  STELLAR_FEE_ESTIMATION_FAILED: 'STELLAR_FEE_ESTIMATION_FAILED',
  STELLAR_FEE_EXCEEDS_LIMIT: 'STELLAR_FEE_EXCEEDS_LIMIT',

  // Validation errors
  STELLAR_INVALID_ASSET: 'STELLAR_INVALID_ASSET',
  STELLAR_ASSET_NOT_FOUND: 'STELLAR_ASSET_NOT_FOUND',
  STELLAR_UNSUPPORTED_OPERATION: 'STELLAR_UNSUPPORTED_OPERATION',
} as const;

// ============== ADAPTER ERRORS - LAYERZERO ==============
export const LAYERZERO_ADAPTER_ERROR_CODES = {
  // Connection errors
  LAYERZERO_CONNECTION_FAILED: 'LAYERZERO_CONNECTION_FAILED',
  LAYERZERO_NETWORK_ERROR: 'LAYERZERO_NETWORK_ERROR',
  LAYERZERO_RPC_ERROR: 'LAYERZERO_RPC_ERROR',

  // Operation errors
  LAYERZERO_OPERATION_FAILED: 'LAYERZERO_OPERATION_FAILED',
  LAYERZERO_INVALID_DESTINATION: 'LAYERZERO_INVALID_DESTINATION',
  LAYERZERO_INSUFFICIENT_GAS: 'LAYERZERO_INSUFFICIENT_GAS',
  LAYERZERO_INVALID_TRANSACTION: 'LAYERZERO_INVALID_TRANSACTION',

  // Quote/estimation errors
  LAYERZERO_QUOTE_FAILED: 'LAYERZERO_QUOTE_FAILED',
  LAYERZERO_GAS_ESTIMATION_FAILED: 'LAYERZERO_GAS_ESTIMATION_FAILED',

  // Validation errors
  LAYERZERO_INVALID_CHAIN: 'LAYERZERO_INVALID_CHAIN',
  LAYERZERO_CHAIN_NOT_SUPPORTED: 'LAYERZERO_CHAIN_NOT_SUPPORTED',
  LAYERZERO_INVALID_TOKEN: 'LAYERZERO_INVALID_TOKEN',
} as const;

// ============== ADAPTER ERRORS - HOP ==============
export const HOP_ADAPTER_ERROR_CODES = {
  // Connection errors
  HOP_CONNECTION_FAILED: 'HOP_CONNECTION_FAILED',
  HOP_NETWORK_ERROR: 'HOP_NETWORK_ERROR',
  HOP_RPC_ERROR: 'HOP_RPC_ERROR',

  // Operation errors
  HOP_OPERATION_FAILED: 'HOP_OPERATION_FAILED',
  HOP_INVALID_ROUTE: 'HOP_INVALID_ROUTE',
  HOP_INSUFFICIENT_LIQUIDITY: 'HOP_INSUFFICIENT_LIQUIDITY',

  // Validation errors
  HOP_INVALID_CHAIN: 'HOP_INVALID_CHAIN',
  HOP_CHAIN_NOT_SUPPORTED: 'HOP_CHAIN_NOT_SUPPORTED',
  HOP_INVALID_TOKEN: 'HOP_INVALID_TOKEN',
} as const;

// ============== VALIDATION ERRORS ==============
export const VALIDATION_ERROR_CODES = {
  INVALID_REQUEST_BODY: 'INVALID_REQUEST_BODY',
  INVALID_QUERY_PARAMS: 'INVALID_QUERY_PARAMS',
  INVALID_ROUTE_PARAMS: 'INVALID_ROUTE_PARAMS',
  VALIDATION_SCHEMA_MISMATCH: 'VALIDATION_SCHEMA_MISMATCH',
  MISSING_REQUIRED_HEADER: 'MISSING_REQUIRED_HEADER',
  INVALID_HEADER_VALUE: 'INVALID_HEADER_VALUE',
} as const;

// ============== AUTH ERRORS ==============
export const AUTH_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
} as const;

// ============== SYSTEM ERRORS ==============
export const SYSTEM_ERROR_CODES = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
} as const;

// ============== UNIFY ALL ERROR CODES ==============
export const ALL_ERROR_CODES = {
  ...BRIDGE_ERROR_CODES,
  ...STELLAR_ADAPTER_ERROR_CODES,
  ...LAYERZERO_ADAPTER_ERROR_CODES,
  ...HOP_ADAPTER_ERROR_CODES,
  ...VALIDATION_ERROR_CODES,
  ...AUTH_ERROR_CODES,
  ...SYSTEM_ERROR_CODES,
} as const;

export type ErrorCode = typeof ALL_ERROR_CODES[keyof typeof ALL_ERROR_CODES];
